#!/usr/bin/env python3
# etl/generate_all_inserts.py
"""
Genera data/normalized/inserts.sql con las 5 tablas rellenas:
 - netflix_titles
 - genres
 - title_genres
 - actors
 - title_actors

Lee (preferencia):
 - data/normalized/netflix_titles_clean.csv
 - data/normalized/title_actors_raw.csv  (opcional, si existe)
 - data/normalized/genres.csv            (opcional)
 - data/normalized/title_genres.csv     (opcional)

También escribe archivos de debug:
 - data/normalized/actors_extracted.csv
 - data/normalized/title_genres_extracted.csv
"""

from pathlib import Path
import pandas as pd
import re
from collections import defaultdict, Counter
from unidecode import unidecode

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
NORMAL = DATA / "normalized"
NORMAL.mkdir(parents=True, exist_ok=True)

CSV_TITLES_PRIMARY = NORMAL / "netflix_titles_clean.csv"
CSV_TITLES_FALLBACK = DATA / "netflix_titles.csv"
CSV_TITLE_ACTORS_RAW = NORMAL / "title_actors_raw.csv"
CSV_GENRES = NORMAL / "genres.csv"
CSV_TITLE_GENRES = NORMAL / "title_genres.csv"

OUT_SQL = NORMAL / "inserts.sql"
ACTORS_CSV = NORMAL / "actors_extracted.csv"
TG_CSV = NORMAL / "title_genres_extracted.csv"

ENCODINGS = ["utf-8", "latin-1", "cp1252"]

def read_csv_try(path):
    if not path.exists():
        return None, f"missing {path.name}"
    last_err = None
    for enc in ENCODINGS:
        try:
            df = pd.read_csv(path, dtype=str, keep_default_na=False, encoding=enc)
            return df, f"ok ({enc}, rows={len(df)})"
        except Exception as e:
            last_err = e
    return None, f"error reading {path}: {last_err}"

def sql_escape(v):
    if v is None: return "NULL"
    s = str(v).strip()
    if s == "": return "NULL"
    s = s.replace("\r"," ").replace("\n"," ")
    s = s.replace("'", "''")
    return f"'{s}'"

def normalize_key(s):
    if not s: return ""
    s = unidecode(str(s)).lower()
    s = " ".join(s.split())
    s = re.sub(r"[^a-z0-9 ]+","", s)
    return s

def split_actors_field(raw):
    if not raw: return []
    s = str(raw).strip()
    if s == "": return []
    # common separators -> comma
    s = re.sub(r"\s*\|\s*", ",", s)
    s = re.sub(r"\s*;\s*", ",", s)
    s = re.sub(r"\s+and\s+", ",", s, flags=re.IGNORECASE)
    # remove surrounding brackets and quotes but preserve inner commas
    s = s.strip()
    parts = [p.strip() for p in re.split(r",", s) if p.strip()]
    cleaned = []
    for p in parts:
        p = re.sub(r"^[\[\(\{\"\']+","", p)
        p = re.sub(r"[\]\)\}\"']+$","", p)
        p = re.sub(r"\s*-\s*.*$","", p).strip()
        p = re.sub(r"\s*\(.*\)$","", p).strip()
        if p:
            cleaned.append(p)
    return cleaned

# ----------------- Read inputs -----------------
df_titles, info_titles = read_csv_try(CSV_TITLES_PRIMARY)
if df_titles is None:
    df_titles, info_titles_fb = read_csv_try(CSV_TITLES_FALLBACK)
    if df_titles is not None:
        info_titles = f"fallback {CSV_TITLES_FALLBACK.name} -> {info_titles_fb}"
    else:
        info_titles = info_titles + f" // fallback {info_titles_fb}"

df_ta_raw, info_ta_raw = read_csv_try(CSV_TITLE_ACTORS_RAW)
df_genres, info_genres = read_csv_try(CSV_GENRES)
df_tg, info_tg = read_csv_try(CSV_TITLE_GENRES)

print("INPUTS:", info_titles, info_ta_raw, info_genres, info_tg)

# ----------------- Prepare output header -----------------
lines = []
lines.append("-- inserts.sql generated by etl/generate_all_inserts.py")
lines.append(f"-- DIAGNOSIS: titles={info_titles}; title_actors_raw={info_ta_raw}; genres={info_genres}; title_genres={info_tg}")
lines.append("SET NAMES utf8mb4;")
lines.append("SET FOREIGN_KEY_CHECKS = 0;")
lines.append("START TRANSACTION;")
lines.append("")

# ---------- netflix_titles ----------
def detect_show_id_col(df):
    if df is None: return None
    for c in df.columns:
        if c.lower() in ("show_id","showid","id"):
            return c
    for c in df.columns:
        if "show" in c.lower() and "id" in c.lower(): return c
    return None

sid_col = detect_show_id_col(df_titles)
titles_created = 0
lines.append("-- netflix_titles")
if df_titles is None:
    lines.append("-- SKIPPED: titles CSV not found")
else:
    if sid_col is None:
        lines.append("-- ERROR: no show_id column detected in titles. Columns: " + ", ".join(df_titles.columns))
    else:
        for _, r in df_titles.iterrows():
            sid = str(r.get(sid_col,"")).strip()
            if not sid: continue
            def gv(*cands):
                for c in cands:
                    if c in df_titles.columns and str(r.get(c,"")).strip():
                        return r.get(c)
                return ""
            type_ = gv("type","Type")
            title = gv("title","name")
            director = gv("director","Director")
            # detect cast-like column
            cast_val = ""
            for c in df_titles.columns:
                if "cast" in c.lower() or "actor" in c.lower() or "starring" in c.lower():
                    v = str(r.get(c,"") or "").strip()
                    if v:
                        cast_val = v
                        break
            country = gv("country","Country")
            date_added = gv("date_added","dateAdded")
            release_year = gv("release_year","releaseYear")
            rating = gv("rating")
            duration_raw = gv("duration_raw","duration")
            description = gv("description","synopsis","summary")
            vals = ",".join([
                sql_escape(sid),
                sql_escape(type_),
                sql_escape(title),
                sql_escape(director),
                sql_escape(cast_val),
                sql_escape(country),
                (sql_escape(date_added) if date_added else "NULL"),
                (str(int(release_year)) if str(release_year).isdigit() else (sql_escape(release_year) if release_year else "NULL")),
                sql_escape(rating),
                sql_escape(duration_raw),
                "NULL", # duration_int (optional)
                "NULL", # duration_unit
                sql_escape(description)
            ])
            cols = ",".join([f"`{c}`" for c in ["show_id","type","title","director","cast","country","date_added","release_year","rating","duration_raw","duration_int","duration_unit","description"]])
            # note: schema's cast column name may be `cast` or `cast_list` — adapt if necessary
            lines.append(f"INSERT IGNORE INTO netflix_titles ({cols}) VALUES ({vals});")
            titles_created += 1
        lines.append(f"-- FILAS netflix_titles generadas: {titles_created}")
lines.append("")

# ---------- genres + title_genres ----------
lines.append("-- genres + title_genres")
genre_set = set()
genre_pairs = []   # (sid, genre)
if df_tg is not None:
    # prefer title_genres.csv pairs
    sidc = None
    gcol = None
    for c in df_tg.columns:
        if c.lower() in ("show_id","showid","id"): sidc = c
        if "genre" in c.lower() or "listed" in c.lower() or "name" in c.lower(): gcol = c
    if sidc is None:
        print("title_genres.csv present but no show_id column detected.")
    else:
        for _, r in df_tg.iterrows():
            sid = str(r.get(sidc,"")).strip()
            if not sid: continue
            if gcol:
                gval = str(r.get(gcol,"")).strip()
                if not gval: continue
                for g in [p.strip() for p in re.split(r",|;|\|", gval) if p.strip()]:
                    genre_set.add(g); genre_pairs.append((sid, g))
elif df_genres is not None:
    # populate from genres.csv
    gcol = next((c for c in df_genres.columns if c.lower() in ("genre_name","genre","name")), df_genres.columns[0])
    for _, r in df_genres.iterrows():
        g = str(r.get(gcol,"")).strip()
        if g: genre_set.add(g)
    # try to extract relations from titles listed_in
    if df_titles is not None:
        list_col = next((c for c in df_titles.columns if "listed" in c.lower() or "genre" in c.lower()), None)
        if list_col:
            for _, r in df_titles.iterrows():
                sid = str(r.get(sid_col,"")).strip()
                if not sid: continue
                tgs = str(r.get(list_col,"")).strip()
                if not tgs: continue
                for g in [p.strip() for p in re.split(r",|;|\|", tgs) if p.strip()]:
                    genre_set.add(g); genre_pairs.append((sid,g))
else:
    # fallback: extract from title listed_in
    if df_titles is not None:
        list_col = next((c for c in df_titles.columns if "listed" in c.lower() or "genre" in c.lower()), None)
        if list_col:
            for _, r in df_titles.iterrows():
                sid = str(r.get(sid_col,"")).strip()
                if not sid: continue
                tgs = str(r.get(list_col,"")).strip()
                if not tgs: continue
                for g in [p.strip() for p in re.split(r",|;|\|", tgs) if p.strip()]:
                    genre_set.add(g); genre_pairs.append((sid,g))

# write genres inserts
gcnt = 0; tgc = 0
if genre_set:
    for g in sorted(genre_set):
        lines.append(f"INSERT IGNORE INTO genres (`genre_name`) VALUES ({sql_escape(g)});")
        gcnt += 1
    if genre_pairs:
        for sid,g in genre_pairs:
            lines.append(f"INSERT IGNORE INTO title_genres (`show_id`, `genre_id`) SELECT {sql_escape(sid)}, `genre_id` FROM genres WHERE `genre_name` = {sql_escape(g)};")
            tgc += 1
lines.append(f"-- FILAS genres: {gcnt}; title_genres: {tgc}")
lines.append("")

# ---------- actors + title_actors ----------
lines.append("-- actors + title_actors")
pairs = []   # (sid, actor_name)

# priority: title_actors_raw.csv if present
if df_ta_raw is not None:
    # expect columns [show_id, actor_name] or similar
    sidc = next((c for c in df_ta_raw.columns if c.lower() in ("show_id","showid","id")), None)
    actorc = next((c for c in df_ta_raw.columns if "actor" in c.lower() or "name" in c.lower()), None)
    if sidc is None:
        print("title_actors_raw.csv present but no show_id column detected.")
    else:
        if actorc:
            for _, r in df_ta_raw.iterrows():
                sid = str(r.get(sidc,"")).strip()
                if not sid: continue
                raw = str(r.get(actorc,"")).strip()
                if not raw: continue
                # raw may contain comma-separated list -> split
                for a in re.split(r",|;|\||\sand\s", raw):
                    a = a.strip()
                    if a:
                        # clean
                        a = re.sub(r"^[\[\(\{\"\']+","", a)
                        a = re.sub(r"[\]\)\}\"']+$","", a)
                        a = re.sub(r"\s*\(.*\)$","", a).strip()
                        pairs.append((sid, a))
        else:
            # try using second column as actor
            cols = [c for c in df_ta_raw.columns if c != sidc]
            if cols:
                for _, r in df_ta_raw.iterrows():
                    sid = str(r.get(sidc,"")).strip()
                    if not sid: continue
                    raw = str(r.get(cols[0],"")).strip()
                    if not raw: continue
                    for a in re.split(r",|;|\||\sand\s", raw):
                        a = a.strip()
                        if a:
                            a = re.sub(r"^[\[\(\{\"\']+","", a)
                            a = re.sub(r"[\]\)\}\"']+$","", a)
                            a = re.sub(r"\s*\(.*\)$","", a).strip()
                            pairs.append((sid, a))

# fallback: extract from df_titles cast column
if not pairs and df_titles is not None:
    cast_col = next((c for c in df_titles.columns if "cast" in c.lower() or "actor" in c.lower() or "starring" in c.lower()), None)
    if cast_col:
        for _, r in df_titles.iterrows():
            sid = str(r.get(sid_col,"")).strip()
            if not sid: continue
            raw = str(r.get(cast_col,"")).strip()
            if not raw: continue
            for a in split_actors_field(raw):
                pairs.append((sid, a))
    else:
        print("No cast column found in titles and no title_actors_raw.csv provided.")

# canonicalize actors and generate inserts
# canonicalization: normalize accents/case and pick most frequent representation
groups = defaultdict(list)
for sid,a in pairs:
    k = normalize_key(a)
    groups[k].append(a)
canonical = {}
for k,names in groups.items():
    cnt = Counter(names)
    canonical[k] = sorted(cnt.items(), key=lambda x:(-x[1], len(x[0]), x[0]))[0][0]
orig_to_canon = {}
for k,names in groups.items():
    for n in set(names):
        orig_to_canon[n] = canonical[k]

unique_actors = sorted(set(canonical.values()))
for a in unique_actors:
    lines.append(f"INSERT IGNORE INTO actors (`actor_name`) VALUES ({sql_escape(a)});")
# title_actors mapping using SELECT to match actor_id
seen = set()
for sid,a in pairs:
    canon = orig_to_canon.get(a, a)
    key = (sid, canon)
    if key in seen: continue
    seen.add(key)
    lines.append(f"INSERT IGNORE INTO title_actors (`show_id`, `actor_id`) SELECT {sql_escape(sid)}, `actor_id` FROM actors WHERE `actor_name` = {sql_escape(canon)};")

lines.append(f"-- FILAS actors: {len(unique_actors)}; title_actors (approx): {len(seen)}")
lines.append("")
lines.append("COMMIT;")
lines.append("SET FOREIGN_KEY_CHECKS = 1;")
lines.append("")

# write output SQL
with open(OUT_SQL, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

# write debug CSVs
if pairs:
    df_actors = pd.DataFrame(pairs, columns=["show_id","actor_name"])
    df_actors.to_csv(ACTORS_CSV, index=False, encoding="utf-8")
if genre_pairs:
    df_tg_out = pd.DataFrame(genre_pairs, columns=["show_id","genre_name"])
    df_tg_out.to_csv(TG_CSV, index=False, encoding="utf-8")

print("Generated:", OUT_SQL)
if pairs:
    print("Actors extracted file:", ACTORS_CSV)
if genre_pairs:
    print("Title-genre pairs file:", TG_CSV)
print("If actors are still missing in the final INSERT run, inspect actors_extracted.csv and title_actors raw to verify parsing.")
